//
//  CallgraphGenApplication.swift
//  callgraphbuilder
//
//  Created by Rachit Prajapati on 2/10/25.
//

import Foundation
import SwiftParser
import OrderedCollections

public class CallgraphGenApplication {
    
    // collects the Swift files from the provided codebase
    public static func collectSwiftFiles(from projectPath: String) -> [URL] {
        
        let fileManager = FileManager.default
        var swiftFiles: [URL] = [] // Storing Swift files
        
        if let enumerator = fileManager.enumerator(atPath: projectPath) {
            for case let file as String in enumerator {
                if file.hasSuffix(".swift") {
                    let fullPath = URL(filePath: projectPath).appendingPathComponent(file)
                    swiftFiles.append(fullPath)
                }
            }
        }
        
        return swiftFiles
    }
    
    // Process Swift files and build a call graph

    public static func processSwiftFiles(_ swiftFiles: [URL], path: String) {
        // Convert file paths to strings for the CallGraphBuilder
        let filePaths = swiftFiles.map { $0.path }
        var processFilesThatContainUIElements = [URL]()
        
        for file in swiftFiles {
            if initiateFilteringToFindFirstFileThatContainsUIElements(filePath: file) {
                processFilesThatContainUIElements.append(file)
            }
        }
        
        // Generate the call graph
       var codebaseCallgraph =  Array<OrderedDictionary<String, [String]>>()
        for fileThatContainsUIElement in processFilesThatContainUIElements {
            let callGraphBuilder = CallGraphBuilder()
            callGraphBuilder.buildGraph(from: fileThatContainsUIElement.path(), in: filePaths)
            print("For file \(fileThatContainsUIElement.lastPathComponent)\n")
            print("Generated Call Graph internallyt:\n")
            codebaseCallgraph.append(callGraphBuilder.callGraph)
           
            for (function, calls) in callGraphBuilder.callGraph {
                
                print("Function: \(function)")
                for call in calls {
                    print("Calls: \(call)")
                }
            }
        }
        print("\n code below\n")
        createCallGraphLoggerFile(at: path, callGraphData: codebaseCallgraph)
        print("\n graph code\n")
    }

    
    // Converts the generated call graph into Swift source code.
    static func exportCallGraphAsCode(codebaseCallgraph: [OrderedDictionary<String, [String]>]) -> String {
        var output = """
        // Generated Call Graph
        // This file was automatically generated by CallgraphGenApplication.
        
        import Foundation 
        
        struct CallGraphNode { 
            var calledFunctions: [String] 
            var executionTime: (Double?, Double?)  // (inclusive, exclusive) execution times
        }

        public class CallGraphLogger {
            static let shared = CallGraphLogger()
            
            var callGraph: [[(String, CallGraphNode)]] = [
        """

        // Transform OrderedDictionary into array of tuples
        for callGraph in codebaseCallgraph {
            output += "\n            [\n"
            for (function, calls) in callGraph {
                let callsLiteral = calls.map { "\"\($0)\"" }.joined(separator: ", ")
                output += "                (\"\(function)\", CallGraphNode(calledFunctions: [\(callsLiteral)], executionTime: (nil, nil))),\n"
            }
            output += "            ],\n"
        }

        output += """
            ]

            private init() {}

            public func updateExecutionTime(for functionName: String, syncTime: Double, asyncTime: Double) {
                for i in callGraph.indices {
                    for j in callGraph[i].indices {
                        if callGraph[i][j].0 == functionName {
                            callGraph[i][j].1.executionTime = (syncTime, asyncTime)
                            return
                        }
                    }
                }
                callGraph.append([
                    (functionName, CallGraphNode(calledFunctions: [], executionTime: (syncTime, asyncTime)))
                ])
            }

            public func printCallGraph() {
                print("----- Call Graph -----")
                for graph in callGraph {
                    for (name, node) in graph {
                        let syncTimeStr = node.executionTime.0.map { "\\($0) sec" } ?? "n/a"
                        let asyncTimeStr = node.executionTime.1.map { "\\($0) sec" } ?? "n/a"
                        print("Function: \\(name) | Sync Time: \\(syncTimeStr) | AsyncTime Time: \\(asyncTimeStr) | Calls: \\(node.calledFunctions)")
                    }
                }
                print("----------------------")
            }
        }

        // Global function to be called by the inserted profiling code.
        public func recordExecutionTime(functionName: String, syncTime: Double, asyncTime: Double) {
            CallGraphLogger.shared.updateExecutionTime(for: functionName, syncTime: syncTime, asyncTime: asyncTime)
            
            // Print the call graph after updating execution time
            CallGraphLogger.shared.printCallGraph()
        }
        """

        return output
    }
    
    // Function to create and inject CallGraphLogger.swift
    static func createCallGraphLoggerFile(at projectPath: String, callGraphData: [OrderedDictionary<String, [String]>]) {
        
        // Step 1: Identify the correct subdirectory that contains Swift files
        guard let sourceFolder = findSourceDirectory(in: projectPath) else {
            return
        }
        
        let filePath = "\(sourceFolder)/CallGraphLogger.swift"
        
        // Generate CallGraphLogger.swift code dynamically
        let generatedCode = exportCallGraphAsCode(codebaseCallgraph: callGraphData)
        
        do {
            // Write the generated code to CallGraphLogger.swift
            try generatedCode.write(to: URL(fileURLWithPath: filePath), atomically: true, encoding: .utf8)
        } catch {
        }
    }
    
    /// Finds the first subdirectory that contains `.swift` files inside the project folder.
    static func findSourceDirectory(in projectPath: String) -> String? {
        let fileManager = FileManager.default
        let projectURL = URL(fileURLWithPath: projectPath)

        do {
            let subdirectories = try fileManager.contentsOfDirectory(at: projectURL, includingPropertiesForKeys: nil)
                .filter { $0.hasDirectoryPath } // Get only directories
            
            for folder in subdirectories {
                let swiftFiles = try fileManager.contentsOfDirectory(atPath: folder.path)
                    .filter { $0.hasSuffix(".swift") }
                
                if !swiftFiles.isEmpty {
                    return folder.path // Return the first folder that contains Swift files
                }
            }
            
        } catch {
        }
        
        return nil
    }
    
    // filters and collects file of Swift format from directory
    public static func initiateFilteringToFindFirstFileThatContainsUIElements(filePath: URL) -> Bool {
        do {
            let fileContents = try String.init(contentsOf: filePath, encoding: .utf8)
            let processedFileContent = fileContents.trimmingCharacters(in: .whitespacesAndNewlines)
            let parsedContent = Parser.parse(source: processedFileContent)
            let buttonIndicator = InteractiveElementFinder(viewMode: .sourceAccurate)
            buttonIndicator.walk(parsedContent)
            
            if buttonIndicator.containsInteractiveElement {
                return true
            } else {
                return false
            }
        } catch {
            print("Error processing finding the first to process that contains button \(error.localizedDescription)")
            return false
        }
    }
}

